version: "3"

services:
    nginx:
        image: nginx:1.13-alpine
        container_name: alerting_web
        ports:
            - "80:80"
        volumes:
            - .:/application
            - ./tools/docker/logs/nginx:/var/log/nginx
            - ./tools/docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
        networks:
            alerting:
                ipv4_address: 172.20.240.10

    php:
        build: ./tools/docker/php-fpm
        container_name: alerting_php
        volumes:
            - .:/application
        networks:
            alerting:
                ipv4_address: 172.20.240.20

    db:
        image: mysql:8.0
        container_name: alerting_db
        ports:
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=alerting
            - MYSQL_USER=dev
            - MYSQL_PASSWORD=dev
        networks:
            alerting:
                ipv4_address: 172.20.240.30

networks:
    alerting:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.20.240.0/24